---
_hotel_id: MAG307
_portal_id: ''
latitude: 42.29792
longitude: -71.39806
name: Magnuson Hotel Framingham
email: ''
phone_number: "--"
address:
  street1: 130 Worcester Rd
  street2: ''
  state: Massachusetts
  city: Framingham
  country: United States
  zip_code: '01702'
